Repository AY2122S2-TIC4002-F18-4/tp2, pull requests merged in 2022-04, with the labels that each got.

#54 47 - Fix inaccurate money limit
  src/main/java/seedu/address/model/person/Money.java
Labels: type.Bug, severity.Low

#55 48 - Money value overflow in UI
  docs/UserGuide.md
Labels: type.Bug, severity.VeryLow

#59 Fix/fix ug error message
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Bug, priority.Low, severity.Low

#61 36 - Add task feature - not saving to storage
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, severity.High

#63 60 - Cannot change task to empty
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug, severity.Medium

#65 64 - Further integrate Task to Person model
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task

#67 66 - UG - add tk/ parameter not set to optional
  docs/UserGuide.md
Labels: type.Bug, severity.Medium

#69 68 - Chia Chun UG
  docs/UserGuide.md
Labels: type.Task

#73 72 - Money Owed Overview does not update after DeleteCommand
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: type.Bug, severity.High

#75 74 - Money Owed Overview does not update after ClearCommand
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug, severity.High

#71 70 - Chia Chun DG
  docs/DeveloperGuide.md
  docs/Logging.md
  docs/diagrams/CommandExecutionSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/MoneyOverviewClassDiagram.puml
  docs/diagrams/MoneyOverviewSequenceDiagramFire.puml
  docs/diagrams/MoneyOverviewSequenceDiagramInit.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/CommandExecutionSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/MoneyOverviewClassDiagram.png
  docs/images/MoneyOverviewSequenceDiagramFire.png
  docs/images/MoneyOverviewSequenceDiagramInit.png
  docs/images/UiClassDiagram.png
Labels: type.Task

#79 78 - Chia Chun PPP
  docs/team/tanchiachun.md
Labels: type.Task

#80 Update help
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, severity.VeryLow
